### ISSUE TITLE
incorrect types value in package.json

### ISSUE THREAD

**Issue by silverprize** [ignlg/simplify-path-js#1]
hi
I found a minor error.
The file name on types in package.json is written incorrectly.

package.json
https://github.com/ignlg/simplify-path-js/blob/main/package.json#L22

typing ts
https://github.com/ignlg/simplify-path-js/blob/main/dist/types/simplify-path.class.d.ts

**Comment by ignlg** [comment]
Oh! Thank you so much for spotting the issue. I will fix it right away 👍

**Comment by ignlg** [comment]
Fixed!

**Comment by silverprize** [comment]
Please republish in a new version.

**Comment by silverprize** [comment]
I installed 1.0.2. Thank you.
